//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH04_Employee_Information
    {
        public int EmployeeID { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpStreetAddress { get; set; }
        public string EmpCity { get; set; }
        public string EmpState { get; set; }
        public string EmpZipCode { get; set; }
        public Nullable<short> EmpAreaCode { get; set; }
        public string EmpPhoneNumber { get; set; }
        public Nullable<System.DateTime> EmpBirthDate { get; set; }
    }
}
