//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH05_Adjusted_Wholesale_Prices
    {
        public int ProductNumber { get; set; }
        public Nullable<decimal> WholesalePrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
    }
}
