//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH08_Orders_With_Products
    {
        public int OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int ProductNo { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<decimal> AmountOwed { get; set; }
    }
}
