//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH10_Customer_Helmets_Vendor_Helmets
    {
        public string FullName { get; set; }
        public string ProductName { get; set; }
        public string RowID { get; set; }
    }
}
