//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH10_Customer_Order_Bikes_UNION_Customer_Order_Helmets
    {
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public string ProdType { get; set; }
    }
}
