//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH18_Customers_Bikes_And_Helmets_Same_Order
    {
        public int CustomerID { get; set; }
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public int OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
