//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH20_Employees_Same_State_Customers
    {
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public string CustFirstName { get; set; }
        public string CustLastName { get; set; }
        public Nullable<short> CustAreaCode { get; set; }
        public string CustPhoneNumber { get; set; }
        public string CustStatus { get; set; }
    }
}
